In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Data.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
Area               0 non-null float64
Oxygen             40 non-null int64
Temperature        40 non-null int64
Humidity           40 non-null int64
Fire Occurrence    40 non-null int64
dtypes: float64(1), int64(4)
memory usage: 1.7 KB


In [4]:
data.head()

Area   Oxygen  Temperature  Humidity  Fire Occurrence
0    NaN      40           45        20                1
1    NaN      50           30        10                1
2    NaN      10           20        70                0
3    NaN      60           45        70                1
4    NaN      30           48        10                1

In [5]:
import numpy as np

In [6]:
data = np.array(data)

In [7]:
data


array([[ nan,  40.,  45.,  20.,   1.],
       [ nan,  50.,  30.,  10.,   1.],
       [ nan,  10.,  20.,  70.,   0.],
       [ nan,  60.,  45.,  70.,   1.],
       [ nan,  30.,  48.,  10.,   1.],
       [ nan,  30.,  48.,  10.,   1.],
       [ nan,  50.,  15.,  30.,   0.],
       [ nan,   5.,  35.,  35.,   0.],
       [ nan,   5.,  20.,  70.,   0.],
       [ nan,  60.,  32.,  17.,   1.],
       [ nan,  30.,  50.,  45.,   1.],
       [ nan,  40.,  55.,  80.,   1.],
       [ nan,  30.,  39., 100.,   0.],
       [ nan,  10.,  12.,  12.,   0.],
       [ nan,  20.,  23.,  23.,   0.],
       [ nan,  60.,  34.,  15.,   1.],
       [ nan,  80.,   4.,  68.,   0.],
       [ nan,  25.,  56.,  79.,   1.],
       [ nan,  12.,  45.,  90.,   0.],
       [ nan,  28.,  43.,  15.,   1.],
       [ nan,  26.,   0.,  32.,   0.],
       [ nan,  32.,  37.,  21.,   1.],
       [ nan,  45.,  48.,  12.,   1.],
       [ nan,  56.,  15.,  65.,   0.],
       [ nan,  67.,  45.,  33.,   1.],
       [ nan,  78.,  49.,

In [8]:
x = data[:,1:-1]

In [11]:
x

array([[ 40.,  45.,  20.],
       [ 50.,  30.,  10.],
       [ 10.,  20.,  70.],
       [ 60.,  45.,  70.],
       [ 30.,  48.,  10.],
       [ 30.,  48.,  10.],
       [ 50.,  15.,  30.],
       [  5.,  35.,  35.],
       [  5.,  20.,  70.],
       [ 60.,  32.,  17.],
       [ 30.,  50.,  45.],
       [ 40.,  55.,  80.],
       [ 30.,  39., 100.],
       [ 10.,  12.,  12.],
       [ 20.,  23.,  23.],
       [ 60.,  34.,  15.],
       [ 80.,   4.,  68.],
       [ 25.,  56.,  79.],
       [ 12.,  45.,  90.],
       [ 28.,  43.,  15.],
       [ 26.,   0.,  32.],
       [ 32.,  37.,  21.],
       [ 45.,  48.,  12.],
       [ 56.,  15.,  65.],
       [ 67.,  45.,  33.],
       [ 78.,  49.,   8.],
       [ 89.,  45.,  18.],
       [ 21.,  12.,  44.],
       [ 11.,  20.,  59.],
       [  1.,  32.,  70.],
       [  5.,  20.,  45.],
       [ 42.,  43.,  20.],
       [ 32.,  60.,  30.],
       [  5.,  15.,   5.],
       [ 20.,  30.,   5.],
       [ 30.,  51.,   2.],
       [ 60.,  60.,  10.],
 

In [12]:
y = data[:,-1]

In [13]:
y

array([1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1.])

In [14]:
x = x.astype('int')

In [15]:
x

array([[ 40,  45,  20],
       [ 50,  30,  10],
       [ 10,  20,  70],
       [ 60,  45,  70],
       [ 30,  48,  10],
       [ 30,  48,  10],
       [ 50,  15,  30],
       [  5,  35,  35],
       [  5,  20,  70],
       [ 60,  32,  17],
       [ 30,  50,  45],
       [ 40,  55,  80],
       [ 30,  39, 100],
       [ 10,  12,  12],
       [ 20,  23,  23],
       [ 60,  34,  15],
       [ 80,   4,  68],
       [ 25,  56,  79],
       [ 12,  45,  90],
       [ 28,  43,  15],
       [ 26,   0,  32],
       [ 32,  37,  21],
       [ 45,  48,  12],
       [ 56,  15,  65],
       [ 67,  45,  33],
       [ 78,  49,   8],
       [ 89,  45,  18],
       [ 21,  12,  44],
       [ 11,  20,  59],
       [  1,  32,  70],
       [  5,  20,  45],
       [ 42,  43,  20],
       [ 32,  60,  30],
       [  5,  15,   5],
       [ 20,  30,   5],
       [ 30,  51,   2],
       [ 60,  60,  10],
       [ 10,  10,  60],
       [  0,  30,   0],
       [ 45,  45,  15]])

In [16]:
y  = y.astype('int')

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, y_train, X_test, Y_text = train_test_split(x,y,test_size=0.3,random_state=0)

In [31]:
log_reg = LogisticRegression

In [32]:
log_reg.fit(X_train, y_train)

TypeError: fit() missing 1 required positional argument: 'y'